stages:
  experiments:
    cmd: python scripts/run_experiments.py
    deps:
      - src/strategies/meta_strategy.py
      - src/models/ml_model.py
      - src/models/reinforcement_learning.py
      - scripts/run_experiments.py
      - src/utils/config.py
    outs:
      - db/experiments/results.json